### ISSUE TITLE
Chyba

### ISSUE THREAD

**Issue by stolfam** [aleswita/DropzoneUploader#1]
TypeError

Argument 1 passed to AlesWita\DropzoneUploader\Factory::setTranslator() must implement interface Nette\Localization\ITranslator, string given, called in C:\xampp\htdocs\temp\cache\Nette.Configurator\Container_35b3513886.php on line 509

celá chyba zde:
https://www.dropbox.com/s/t7erfgc2oi92grf/TypeError_%20Argument%201%20passed%20to%20AlesWita_DropzoneUploader_Factory__setTranslator%28%29%20must%20implement%20interface%20Nette_Localization_ITranslator%2C%20string%20given%2C%20called%20in%20C__xampp_htdocs_temp_cache_Nette.Configurator_Cont.html?dl=0

**Comment by aleswita** [comment]
Muzes ukazat config, jak komponentu registrujes u sebe v aplikaci?

**Comment by stolfam** [comment]
Kdyz jsem doinstaloval rozsireni Kdyby/Translator tak uz to zaclo normalne
fungovat, takze sem spise chtel upozornit na to, jestli tam neni nejaka
zavislost o ktery by meli uzivatele pripadne vedet :)
Ale je mozny ze mam blbe config - s Nette teprve zacinam..

Kazdopadne moc dekuju za zpravu! :-)

2018-03-06 15:28 GMT+01:00 Aleš <notifications@github.com>:

**Comment by stolfam** [comment]
Aha, tak on se neodeslal...
Tak ho přikládám tady:
https://www.dropbox.com/s/78lzlvzbai38a66/config.neon?dl=0

a tady ještě chyba z produkčního serveru se kterou si teda taky nevím rady, protože na localhostu vše běželo OK (promazal sem i cache):
https://www.dropbox.com/s/96jo33zxd0dvt3d/exception--2018-03-06--16-39--80aa39c701.html?dl=0

**Comment by stolfam** [comment]
Tak ono to bylo verzí PHP.. na produkčním je pouze 7.0. Omlouvám se za zmatky :)

**Comment by aleswita** [comment]
@stolfam ad translator, nejak jsem zil v domeni ze Nette vytvari nejaky svuj default translator.. budu s tim pocitat v pristi verzi, kde to opravim

**Comment by filisko** [comment]
I couldn't understand anything guys but I had the same problem, any help?

**Comment by stolfam** [comment]
just create (PHP) class (like below) and add service into the config.neon .. it solved my problem

// create file MyDefaultTranslator.php
class MyDefaultTranslator implements Nette\Localization\ITranslator
{
    public function translate($message, $count = null)
    {
        return $message.;
    }
}

read more hear https://doc.nette.org/en/2.4/localization
