### ISSUE TITLE
Problem s instalaciou

### ISSUE THREAD

**Issue by ejdzipi** [aleswita/DropzoneUploader#2]
Tento balicek nie je mozne nainstalovat, kedze obsahuje dependency na nette/utils ~2.4
V mojej app pouzivam nette/utils ^2.5
@aleswita mohol by si prosim updatnut verzie dependencies? Dakujem

**Comment by aleswita** [comment]
Zkus posledni verzi (ted jsem ji vydal).

**Comment by ejdzipi** [comment]
Perfektne, problem vyrieseny, dik :)
